version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: >
      Raw dataset containing transactional, product, and shipping data for Greenweez.
      Used to calculate financial metrics such as daily sales, margins, and operational costs.
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: >
          Contains sales transactions. Each row represents one product_id included in an order_id.
          Used for analyzing basket composition, revenue, and margin calculations.
        loaded_at_field: CAST(date_date AS TIMESTAMP)
        freshness:
            warn_after: {count: 90, period: day}
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: Date of purchase for the order.
          - name: orders_id
            description: Unique identifier for the order (transaction level).
          - name: pdt_id
            description: Unique identifier for the product sold.
            tests:
            - not_null
          - name: revenue
            description: Revenue generated by the product in this order line.
      - name: product
        identifier: raw_gz_product
        description: >
          Product catalog data including purchase price for margin calculation.
        columns:
          - name: products_id
            description: Unique identifier for the product (joins with sales table).
          - name: purchSE_PRICE
            description: Purchase price (cost) of the product for Greenweez.
      - name: ship
        identifier: raw_gz_ship
        description: >
          Shipping and logistics data per order, including fees charged to customers
          and internal costs incurred by Greenweez.
        columns:
          - name: orders_id
            description: Unique identifier for the order (joins with sales table).
            tests:
            - not_null
            - unique
          - name: shipping_fee
            description: Shipping fee charged to the customer.
          - name: shipping_fee_1
            description: Duplicate of shipping_fee (data quality check required).
          - name: logCost
            description: Logistics cost incurred by Greenweez (carrier cost).
          - name: ship_cost
            description: Internal shipping cost for Greenweez operations.